name: Pull latest changes from upstream
on:
  schedule:
    # Run every day at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:
    # Allow manual triggering of the workflow
jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      # Checkout the current repository
      - uses: actions/checkout@v3
        with:
          # Fetch all history for all branches and tags
          fetch-depth: 0
      # Add the upstream repository as a remote
      - run: git remote add upstream https://github.com/alphagov/govuk-prototype-kit.git
      # Pull the latest changes from the main branch of the upstream repository
      - run: git pull upstream main
      # Push the changes to the origin repository
      - run: git push origin main
