name: deploy

on:
  push:
    branches:
      - master
  # Add this line to enable manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.14 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: blank-prototype1
          heroku_email: ben.raine@engineering.digital.dwp.gov.uk
